# Generated by Django 4.1.2 on 2022-12-13 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_rename_texto_entrada_cuerpo_entrada_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='clasificacion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
