# Generated by Django 4.1.2 on 2022-12-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_entrada_clasificacion_alter_libro_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('Arte', 'Arte'), ('Biografía', 'Biografía'), ('Negocios', 'Negocios'), ('Infantil', 'Infantil'), ('Comics', 'Comics'), ('Cocina', 'Cocina'), ('Fantasía', 'Fantasía'), ('Ficción', 'Ficción'), ('Novela gráfica', 'Novela gráfica'), ('Ficción histórica', 'Ficción histórica'), ('Histora', 'Histora'), ('Terror', 'Terror'), ('Música', 'Música'), ('Misterio', 'Misterio'), ('Poesía', 'Poesía'), ('Piscología', 'Piscología'), ('Romántico', 'Romántico'), ('Ciencia', 'Ciencia'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Autoayuda', 'Autoayuda'), ('Deportes', 'Deportes'), ('Suspenso', 'Suspenso'), ('Turismo', 'Turismo'), ('Juvenil', 'Juvenil')], max_length=100),
        ),
    ]
