# Generated by Django 4.1.2 on 2022-12-13 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_entrada_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.libro'),
        ),
    ]
