# Generated by Django 4.1.2 on 2022-12-13 22:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_entrada_id_alter_entrada_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
