# Generated by Django 4.1.2 on 2022-12-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0002_perfil'),
        ('AppBlog', '0007_alter_entrada_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLogin.perfil'),
        ),
    ]
