# Generated by Django 4.1.2 on 2022-12-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_rename_author_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='autor',
            field=models.TextField(),
        ),
    ]
