# Generated by Django 4.1.2 on 2022-12-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_entrada_editado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='editado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
