# Generated by Django 4.1.2 on 2022-12-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0009_remove_perfil_avatar'),
        ('AppBlog', '0014_alter_entrada_editado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLogin.perfil'),
        ),
    ]
