# Generated by Django 4.1.2 on 2022-12-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0015_alter_mensaje_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='editado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
