# Generated by Django 4.1.2 on 2022-12-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0017_alter_comentario_fecha_alter_entrada_editado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='clasificacion',
            new_name='calificacion',
        ),
    ]
