# Generated by Django 4.1.2 on 2022-12-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0018_rename_clasificacion_entrada_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='editado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
