# Generated by Django 4.1.2 on 2022-12-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0019_alter_entrada_editado_alter_entrada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='editado',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
