# Generated by Django 4.1.2 on 2022-12-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogin', '0008_rename_imagen_perfil_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
    ]
